services:
  auth:
    image: "876622472841.dkr.ecr.ap-east-1.amazonaws.com/remy/auth-service"
    ports:
      - "8081:8080"
    environment:
      DB_URL: "jdbc:mysql://host.orb.internal:3306/authdb"
      DB_USER: wws
      DB_PASS: "wws_password#2025"
      JWT_SECRET: "your-very-long-jwt-secret-string-2025-your-very-long-jwt-secret-string-2025"
      USER_SERVICE_URL: "http://host.orb.internal:8080"